### ISSUE TITLE
British vs. American spelling

### ISSUE THREAD

**Issue by xoen** [jnioche/carbonintensity-api#19]
Should we pick one and stick to it for consistency?

We now have a combination of the two:
- traits like `Serialize`, `Deserialize`, `DeserializeOwned` have American spelling
- attributes like `serde_with::skip_serializing_none` have American spelling
- some of our internal functions like `normalise_dates()` have British spelling...
- ...some like `deserialize_power_data_test()` have American spelling (although admittedly this is something [I just introduced in this PR](https://github.com/jnioche/carbonintensity-api/pull/18/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R345) - we should probably)
- comments are also inconsistency

I don't think it hugely matter but it would be good to pick one and stick to it :)

FWIW IMHO maybe it would be best to stick to the American spelling given most of the 3rd party crates are bound to have the American spelling anyway.
Although I appreciate the irony of this being a crate for the Carbon Intensity API for **_Great Britain_** 😬. Maybe this is a good argument for using the British spelling? (even tho inevitably we'd have a mixture of the two if we go this route).

**Comment by jnioche** [comment]
British, please! It is the GB carbon api ;-)
